--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jacobpina/Pictures/Wallpapers/0pm4i5mk71ua1.png"

-- Special
background="#0A1117"
foreground="#b9cdd0"
cursor="#b9cdd0"

-- Colors
color0="#0A1117"
color1="#36484F"
color2="#395664"
color3="#47595C"
color4="#51686B"
color5="#5E7B83"
color6="#75999F"
color7="#b9cdd0"
color8="#818f91"
color9="#36484F"
color10="#395664"
color11="#47595C"
color12="#51686B"
color13="#5E7B83"
color14="#75999F"
color15="#b9cdd0"
