# Shell variables
# Generated by 'wal'
wallpaper='/home/jacobpina/Pictures/Wallpapers/0pm4i5mk71ua1.png'

# Special
background='#0A1117'
foreground='#b9cdd0'
cursor='#b9cdd0'

# Colors
color0='#0A1117'
color1='#36484F'
color2='#395664'
color3='#47595C'
color4='#51686B'
color5='#5E7B83'
color6='#75999F'
color7='#b9cdd0'
color8='#818f91'
color9='#36484F'
color10='#395664'
color11='#47595C'
color12='#51686B'
color13='#5E7B83'
color14='#75999F'
color15='#b9cdd0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
