# Shell variables
# Generated by 'wal'
wallpaper='/home/jacobpina/Pictures/Wallpapers/1.png'

# Special
background='#45494c'
foreground='#97c8b7'
cursor='#97c8b7'

# Colors
color0='#45494c'
color1='#A73FB1'
color2='#BB469A'
color3='#966B83'
color4='#B042A7'
color5='#C94A8B'
color6='#CC6784'
color7='#97c8b7'
color8='#698c80'
color9='#A73FB1'
color10='#BB469A'
color11='#966B83'
color12='#B042A7'
color13='#C94A8B'
color14='#CC6784'
color15='#97c8b7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
